export const environment = {
  name: 'demo',
  production: false,
  shouldEncrypt: true,
  appHostUrl: 'https://fiyu-jankec-demo.fiyu.online',
  userModuleApiUrl: 'https://fiyu-jankec-demo-user.fiyu.online/user',
  organizationModuleApiUrl: 'https://fiyu-jankec-demo-organization.fiyu.online/organization',
  platformModuleApiUrl: 'https://fiyu-jankec-demo-platform.fiyu.online/platform',
  crmModuleApiUrl: 'https://fiyu-jankec-demo-crm.fiyu.online/crm',
  nmmModuleApiUrl: 'https://fiyu-jankec-demo-nmm.fiyu.online/nmm',
  dmmModuleApiUrl: 'https://fiyu-jankec-demo-document.fiyu.online/dmm',
  emmModuleApiUrl: 'https://fiyu-jankec-demo-email.fiyu.online/emm',
  jwtClientId: '',
  jwtClientSecret: '',
  azureAuthEnabled: false,
  azureAuthClientId: '',
  azureAuthTenantId: '',
  firebase: {
    apiKey: '',
    authDomain: '',
    databaseURL: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
    measurementId: '',
  },
  firebaseVapidKey: '',
  firebaseRecaptchaSiteKey: '',
  firebaseRecaptchaSecretKey: '',
  logToLoki: false,
  logstashHostUrl: '',
  lokiLogUrl: '',
};
