export const environment = {
  name: 'dev',
  production: false,
  shouldEncrypt: false,
  appHostUrl: 'https://fiyu-jankec-dev.fiyu.online',
  userModuleApiUrl: 'https://fiyu-jankec-dev-user.fiyu.online/user',
  organizationModuleApiUrl: 'https://fiyu-jankec-dev-organization.fiyu.online/organization',
  platformModuleApiUrl: 'https://fiyu-jankec-dev-platform.fiyu.online/platform',
  crmModuleApiUrl: 'https://fiyu-jankec-dev-crm.fiyu.online/crm',
  nmmModuleApiUrl: 'https://fiyu-jankec-dev-nmm.fiyu.online/nmm',
  dmmModuleApiUrl: 'https://fiyu-jankec-dev-document.fiyu.online/dmm',
  emmModuleApiUrl: 'https://fiyu-jankec-dev-email.fiyu.online/emm',
  jwtClientId: 'getihub_ui',
  jwtClientSecret: '217YlCPsF7O9OCNK3pLfESdtf6jKONYoXc2Xx8TJTCi2WEZs49',
  azureAuthEnabled: false,
  azureAuthClientId: '',
  azureAuthTenantId: '',
  firebase: {
    apiKey: '',
    authDomain: '',
    databaseURL: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
    measurementId: '',
  },
  firebaseVapidKey: '',
  firebaseRecaptchaSiteKey: '',
  firebaseRecaptchaSecretKey: '',
  logToLoki: false,
  logstashHostUrl: '',
  lokiLogUrl: '',
};
